vagrant_api_version: "2"
host_os: "generic/rhel9"
default_user: greg
default_user_password: passwordRhel9

ssh_key: 
  copy_ssh_pub_key: true
  pub_key_name: vagrant-greg.pub
  key_name: vagrant-greg
  pub_key_path: ~/.ssh/
  pub_key_destination: /tmp/

ssh_conf_file: 
  path: templates/ssh_conf.erb
  destination_full_path: ./ssh_config

servers: 
  control: 
    controller: 
      memory: "4GiB"
      cpus: "4"
      ip: "172.25.250.8"

  managed_nodes:
    node1:
      memory: 2000
      cpus: 2
      ip: "172.25.250.9"
    node2:
      memory: 2000
      cpus: 2
      ip: "172.25.250.10"
    node3:
      memory: 2000
      cpus: 2
      ip: "172.25.250.11"
    node4:
      memory: 2000
      cpus: 2
      ip: "172.25.250.12"
    node5:
      memory: 2000
      cpus: 2
      ip: "172.25.250.13"

shell_commands: | 
  ls -ltra /tmp/ >> /tmp/lista.txt
  date >> /tmp/lista.txt


shell_scripts:
  add_default_user: 
    description: "add a default user, this is a simple script to add a default user for managing nodes with Ansible."
    script_path: scripts/add_user.sh
  copy_ssh_pub: 
    description: |
      script to copy a given ssh pub to a vagrant server.
    script_path: scripts/copy_ssh_pub.sh
